services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lager
  app:
    build: .
    depends_on:
      - db
    environment:
      DOCKER: true
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
      DB_DATABASE: lager
