
# volumes: (so the database can persist between docker restarts)

services:
  db:
    hostname: db
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    depends_on:
      - db
    build: .
    ports:
      - "5001:5000"
    environment:
      DOCKER: true
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
