
# volumes: (so the database can persist between docker restarts)

services:
  db:
    restart: unless-stopped
    hostname: db
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    restart: unless-stopped
    build: .
    ports:
      - "5001:5000"
    environment:
      DOCKER: true
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 8080
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
